### ISSUE TITLE
Log Monitoring pattern matching

### ISSUE THREAD

**Issue by pitcha** [Appdynamics/log-monitoring-extension#2]
I am using Log Monitoring extension on Windows Server 2012. I am using the extension to monitoring SQL Server 2012 ERRORLOG. I am trying to check occurrences of Severity: 14 which is user logon error.

I've tried multiple patterns on regular expression but the dashboard is not showing the occurence in the metric browser. Below are some of the patterns that I used:

1. Set `matchExactString: false`

```
logs:
  - displayName: "SQL_ERROR_LOG"
    logDirectory: "D:\\MSSQL\\Log"
    logName: "ERRORLOG"
    searchStrings:
      - displayName: "Severity_14"
        pattern: "Severity: 14"
        matchExactString: false
        caseSensitive: false
metricCharacterReplacer:
    - replace: ":"
      replaceWith: ";"
    - replace: "\\|"
      replaceWith: "#"

noOfThreads: 10
threadTimeOut: 60
```

2. Regular expression on pattern "Severity: 14 \\w+"
```
logs:
  - displayName: "SQL_ERROR_LOG"
    logDirectory: "D:\\MSSQL\\Log"
    logName: "ERRORLOG"
    searchStrings:
      - displayName: "Severity_14"
        pattern: "Severity: 14\\w+"
        matchExactString: false
        caseSensitive: false

metricCharacterReplacer:
    - replace: ":"
      replaceWith: ";"
    - replace: "\\|"
      replaceWith: "#"

noOfThreads: 10
threadTimeOut: 60
```

3. Regular expression on pattern "Severity: 14 \\w*"

```
logs:
  - displayName: "SQL_ERROR_LOG"
    logDirectory: "D:\\MSSQL\\Log"
    logName: "ERRORLOG"
    searchStrings:
      - displayName: "Severity_14"
        pattern: "Severity: 14\\w*"
        matchExactString: false
        caseSensitive: false
metricCharacterReplacer:
    - replace: ":"
      replaceWith: ";"
    - replace: "\\|"
      replaceWith: "#"

noOfThreads: 10
threadTimeOut: 60
```

4. Set `matchExactString: true`

Any help would be very much appreciated.
